// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jocinsvfukmwnvqplxhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvY2luc3ZmdWttd252cXBseGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MzM5MDMsImV4cCI6MjA1MDUwOTkwM30.DiDbBFKLKmeLFOx_esvwBdAWeu39MEbsM42R0ymp6YE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);